
CREATE TABLE "PERS_STAGING.PER_STG_TABLE8" (
	"Lat" FLOAT, 
	"Lon" FLOAT, 
	"Txt" TEXT, 
	"Nam" TEXT, 
	"Add" TEXT, 
	"Job" TEXT, 
	"ROW" TEXT, 
	"UPDATED_AT" DATETIME, 
	"VALID_FROM_DATE" DATETIME, 
	"VALID_TO_DATE" DATETIME
)

